// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201127043604_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ef3044c-7254-414c-8e79-9971d672091b"),
                            Email = "Barry@gmail.com",
                            Name = "Barry",
                            Password = "newpassword"
                        },
                        new
                        {
                            Id = new Guid("dd93ffaa-97df-44e3-81e3-5caf8c42abc2"),
                            Email = "roboto@gmail.com",
                            Name = "Mr. Roboto",
                            Password = "youllneverguessthis"
                        });
                });

            modelBuilder.Entity("Domain.List", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("Domain.ListItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Desc")
                                .IsRequired();

                            b1.Property<Guid>("ListId");

                            b1.Property<string>("Url");

                            b1.HasKey("ItemId");

                            b1.HasIndex("ListId");

                            b1.ToTable("ListItem");

                            b1.HasOne("Domain.List")
                                .WithMany("Items")
                                .HasForeignKey("ListId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
